name: Test Daily

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  create_issue_if_failure:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Create an issue for test failure
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Test failure detected"
          content-filepath: test_output.log
          labels: bug
